#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use philiplarsson\Noty\Commands\NewCommand;
use philiplarsson\Noty\Commands\CompileCommand;

use Symfony\Component\Console\Application;

$app = new Application('Note utility app', "1.0");

$app->add(new NewCommand());
$app->add(new CompileCommand());

$app->run();

